### PR TITLE
data download and conversion to lance is automated

### PR DESCRIPTION
**Pull request by viplismism**

### CODE REVIEW

**Comment by tanaymeh** [comment]
@vipul-maheshwari Code looks good to me but can you execute the notebook so it shows the cell output under each cell and also that the model is indeed training well?

**Comment by viplismism** [comment]
@tanaymeh will do it today! Thanks

**Comment by viplismism** [comment]
@tanaymeh it's done! Can you review it and merge!

**Review by AyushExel — APPROVED** [review]

**Comment by tanaymeh** [comment]
@vipul-maheshwari In your notebook's `CustomImageDataset`, the below two calls to the Lance dataset can be just one single call.

This -
```python
raw_img = self.ds.take([idx], columns=['image']).to_pydict()
img_data = raw_img['image'][0]

raw_label = self.ds.take([idx], columns=['label']).to_pydict()
label = raw_label['label'][0]
```

Can be just this -
```python
raw_data = self.ds.take([idx], columns=['image', 'label']).to_pydict()
img_data, label = raw_data['image'][0], raw_data['label'][0]
```

This would essentially cut down the time taken to load individual image, label pair in half (since we are doing one call instead of two separate calls).

**Comment by viplismism** [comment]
@tanaymeh missed the cell's part. Thanks for pointing out! Changing it

**Comment by tanaymeh** [comment]
@vipul-maheshwari Did you run the entire notebook again with the optimised dataset to show the new timings?

**Pull request merged**
